---
# tasks file for wordpress

   - name: "To Deploy Wordpress - Installing HTTPD/Mariadb/PHP"
     yum:
      name: "{{ item }}"
      state: present
     with_items:
       - httpd
       - php
       - mariadb-server
       - MySQL-python
       - php-mysql

   - name: "To Deploy Wordpress - Adding HTTPD Configuration"
     template:
      src: virtualhost.tmpl
      dest: "/etc/httpd/conf.d/{{ domain }}.conf"

   - name: "To Deploy Wordpress - Creating Document Root"
     file:
      path: "/var/www/html/{{ domain }}"
      state: directory
      owner: apache
      group: apache

   - name: "To Deploy Wordpress - Downloading Wordpress contents"
     get_url:
      url: https://wordpress.org/wordpress-4.9.2.tar.gz
      dest: /tmp/wordpress.tar.gz

   - name: "To Deploy Wordpress - Extracting"
     unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /tmp/
      remote_src: yes

   - name: "To Deploy Wordpress - Moving contents to Document root"
     copy:
      src: /tmp/wordpress/
      dest: "/var/www/html/{{ domain }}"
      remote_src: yes

   - name: "To Deploy Wordpress - Uploading wp-config.php"
     template:
       src: wp-config.php.tmpl
       dest: "/var/www/html/{{ domain }}/wp-config.php"
   - name: "To Deploy Wordpress - Restarting/Enabling Mariadb"
     service:
      name: mariadb
      state: restarted
      enabled: yes


   - name: "To Deploy Wordpress - Changing mysql root password"
     ignore_errors: yes
     mysql_user:
      login_user: root
      login_password: ''
      user: root
      password: "{{ mysql_pass }}"
      host_all: yes

   - name: "To Deploy Wordpress - Removing Anonymous Users"
     mysql_user:
      login_user: root
      login_password: "{{ mysql_pass }}"
      user: ''
      host_all: yes
      state: absent

   - name: "To Deploy Wordpress - Creating Database"
     mysql_db:
      login_user: root
      login_password: "{{ mysql_pass }}"
      name: "{{ db_name }}"
      state: present

   - name: "To Deploy Wordpress - Creating new DB User"
     mysql_user:
      login_user: root
      login_password: "{{ mysql_pass }}"
      user: "{{ new_user }}"
      state: present
      password: "{{ db_pass }}"
      host: localhost
      priv: "{{ db_name }}.*:ALL"

   - name: "To Deploy Wordpress - Post Installation Restart"
     service:
       name: "{{ item }}"
       state: restarted
     with_items: 
         - httpd
         - mariadb
